services:
  - type: web
    name: stream-capture
    env: python
    plan: free
    buildCommand: apt-get update && apt-get install -y ffmpeg
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
